### ISSUE TITLE
Long messages get cut off (invisibly to user).

### ISSUE THREAD

**Issue by shurcooL** [pavben/WebIRC#23]
See real world example in the following exchange.

![image](https://cloud.githubusercontent.com/assets/1924134/5953189/616be6e8-a73a-11e4-9f1c-dda62888339f.png)

Just to confirm, here's the same long message sent to myself; note that what I receive is cut off.

![image](https://cloud.githubusercontent.com/assets/1924134/5953226/e3b83368-a73a-11e4-8351-01e6ad6a7a80.png)

I don't know IRC details, like whether the 512 byte limit is a server parameter or a hardcoded IRC protocol issue, but, in order of priority:

1. User shouldn't be made unaware their message is sent partially.
2. Perhaps something can happen aside from failing to send entire message, like split it into multiple messages, if that's reasonable automatic behavior.

/cc @dominikh Thanks for helping with this bug report.

**Comment by dominikh** [comment]
The 512 byte limit is inherent in the IRC protocol, and most servers adhere to it. Do note that the limit does not just apply to the text content the user wrote, but also all parts of the protocol (the prefix, the destination, the whitespace in between, …).

**Comment by shurcooL** [comment]
Some further suggestions from @dominikh:

> \<dominikh\> and tell him to just split the messages. the client knows the prefix (by calculating it), the destination and the message
> \<dominikh\> any good client does that nowadays

**Comment by shurcooL** [comment]
Nicely done!
