### ISSUE TITLE
No way to configure server host

### ISSUE THREAD

**Issue by nskaggs** [pavben/WebIRC#25]
Not being able to bind to the server ip causes issues during deployment. For example, I've created a quickstart for openshift, but it won't work unless it can bind to the proper ip.

https://github.com/nskaggs/openshift-webirc

You can see the horrible hack I did to workaround this:

https://github.com/nskaggs/WebIRC/commit/bd6916f24bb7901152a554a0419ead06835abfb2

Would it be possible to simply allow you to set an IP in the config.json?

**Comment by pavben** [comment]
Note that the fix is in the harmony branch. I'll be merging it into master soon as it seems to be stable.
