### ISSUE TITLE
* Connecting to 127.0.0.1:8063 HTTP/1.1 400 Bad Request Content-Type: text/plain Connection: close * Disconnected

### ISSUE THREAD

**Issue by ghost** [pavben/WebIRC#30]
Hello Pavben,

Thanks for this awesome software, I am trying to connect to my mattermost server (chat application) on my localhost. I used the command 
"/server 127.0.0.1 8063 eeee 1234"

Below is the error is get in the browser
- Connecting to 127.0.0.1:8063
  HTTP/1.1 400 Bad Request
  Content-Type: text/plain
  Connection: close
- Disconnected

Also in the console, i get this

> WebIRC@0.0.1 start /home/v3nd1tt/WebIRC
> babel-node main.js

debug: Logger initialized with logLevelConsole info and logLevelFile data
info: WebIRC is listening for https connections on port 28443
info: WebIRC started
info: WebSocket connection established: Z9XYrTo_0CH46u8_ANHpyxi1O3Auttjd
info: WebSocket disconnected
info: WebSocket connection established: Z9XYrTo_0CH46u8_ANHpyxi1O3Auttjd
info: User data saved
info: WebSocket disconnected
info: WebSocket connection established: Z9XYrTo_0CH46u8_ANHpyxi1O3Auttjd
info: User data saved
info: Chatbox send lines=[/server 127.0.0.1 8063 eeee 1234], exec=true, entityId=2
info: Connected to server 127.0.0.1:8063
data: SEND: PASS eeee 1234
data: SEND: NICK mynick
data: SEND: USER webirc webirc 127.0.0.1 :webirc
data: Line: HTTP/1.1 400 Bad Request
data: Line: Content-Type: text/plain
data: Line: Connection: close
data: Line: 
info: Disconnected from server: 127.0.0.1:8063
info: User data saved
info: User data saved

Kindly help me fix what i may be doing wrong.

**Comment by dmitshur** [comment]
Hey @Ewurama,

You said:

> I am trying to connect to my mattermost server

Can you elaborate on that? WebIRC is an IRC client, and it can only connect to IRC servers. Mattermost appears to be different protocol for messaging. Does it also have an IRC protocol that you can connect to? Are other IRC clients able to connect to it successfully? Or did you miss the part where WebIRC is a (persistent, web) IRC client?

**Comment by ghost** [comment]
Hello @shurcooL ,

Mattermost has an irc server, I installed and have been able to connect to it successfully on port 6667. Thanks a lot. However, I would like  an existing web app on the irc client as well. In the end i want to connect both my mattermost server and webapplication through the irc client. 
So far i can access mattermost through this WebIRC. Because mattermost has an irc server called matterircd which i used.
My web application has no irc server, could you assist me figure out how best to access my we app in ircClinet like this webIRC ?

**Comment by pavben** [comment]
The "web" in WebIRC refers to how you access the IRC client, and the "IRC" refers to how it connects to servers. You are correct in using the IRC client to connect to the IRC server, but IRC clients do not connect to servers with non-IRC protocols. I'm not sure what exactly you're trying to accomplish, but try using the web browser to access port 8063 instead of going through an IRC client. I'm also not familiar with mattermost, but consider reaching out to them or their community as they may have more context on that.

**Comment by ghost** [comment]
@pavben   Thanks but the issue with mattermost has been fixed now. i used matterircd which is a an irc adapter for connection to mattermost server. So the issue on mattermost and WebIRC is resolved. Thanks.

Current issue is how i can connect to an existing web app through irc client. this means i will need to connect to my web application using IRC protocols. That is where i need help with. I am quite new to IRC and would really appreciate your assistance.

Ewurama.

**Comment by pavben** [comment]
Sorry for the late reply. I'll reiterate that IRC clients connect only to IRC servers, not web servers. If you have additional questions related to mattermost/matterircd, look up how to find their support or community -- we have no familiarity with it here.
